Traceback (most recent call last):
  File "rxn_chk.py", line 51, in <module>
    check_rct_gra()
  File "rxn_chk.py", line 32, in check_rct_gra
    for zma_fs in ZMA_MANAGERS:
  File "/lcrc/project/CMRP/amech/autofile/autofile/fs.py", line 1193, in iterate_managers
    for pth in iterate_paths(pfx, keys):
  File "/lcrc/project/CMRP/amech/autofile/autofile/fs.py", line 1187, in iterate_paths
    yield from iterate_paths(pfx_, keys)
  File "/lcrc/project/CMRP/amech/autofile/autofile/fs.py", line 1184, in iterate_paths
    fs_ = _manager(pfx, key)
  File "/lcrc/project/CMRP/amech/autofile/autofile/fs.py", line 1141, in _manager
    fs_ = FILE_SYSTEM_MANAGER_DCT[key](pfx)
  File "/lcrc/project/CMRP/amech/autofile/autofile/fs.py", line 265, in theory
    leaf_ds = data_series.theory_leaf(prefix)
  File "/lcrc/project/CMRP/amech/autofile/autofile/schema/data_series.py", line 125, in theory_leaf
    loc_dfile=loc_dfile, root_ds=root_ds)
  File "/lcrc/project/CMRP/amech/autofile/autofile/model.py", line 94, in __init__
    'Path is not a dir: {}'. format(prefix)
AssertionError: Path is not a dir: /lcrc/project/PACC/AutoMech/data/save/RXN/C10H19.CH4/BPHMUIRWCRKOCQ/0_0/2_1/YJOCEBFMSA-N/C10H20.CH3/OWKRVKMVNTUISO/0_0/1_2/GZOLSCHFSA-N/2
